
markdown: kramdown

highlighter: rouge
url: https://morvanzhou.github.io/
exclude: ['README.md']


# collection and their defaults

collections:
  front-pages:
    output: true
  loop-description:
    output: false
  tutorials:
    output: true
    permalink: /:collection/:path/
  table-contents:
    output: true
    permalink: /tutorials/:path/


defaults:
  - scope:
      path: "_front-pages"
    values:
      layout: front-page

  - scope:
      path: "_table-contents"
    values:
      layout: table-of-contents

  - scope:
      path: "_tutorials"
      type: posts
    values:
      layout: tutorial-post
      editor: 莫烦
      author: 莫烦
      author-link: "#"
      comments: true
      published: true

  # module descriptions
  - scope:
      path: "_loop-description/python-basic"
    values:
      module: python-basic
  - scope:
      path: "_loop-description/home"
    values:
      module: home
  - scope:
      path: "_loop-description/data-manipulation"
    values:
      module: data-manipulation
  - scope:
      path: "_loop-description/machine-learning"
    values:
      module: machine-learning
  - scope:
      path: "_loop-description/others"
    values:
      module: others



  # tutorial default
  - scope:
      path: "_tutorials/machine-learning/ML-intro"
    values:
      layout: tutorial-post
      series: 有趣的机器学习
      tut-permalink: /tutorials/machine-learning/ML-intro/
      category: ML-intro
      keywords: 机器学习, 简介, 动画

  - scope:
      path: "_tutorials/machine-learning/reinforcement-learning"
    values:
      layout: tutorial-post
      series: 强化学习 Reinforcement Learning
      tut-permalink: /tutorials/machine-learning/reinforcement-learning/
      category: reinforcement-learning
      keywords: reinforcement learning, 强化学习, tensorflow

  - scope:
      path: "_tutorials/machine-learning/evolutionary-algorithm"
    values:
      layout: tutorial-post
      series: 进化算法 Evolutionary Algorithm
      tut-permalink: /tutorials/machine-learning/evolutionary-algorithm/
      category: evolutionary-algorithm
      keywords: evolutionary algorithm, 进化算法, 遗传算法, genetic algorithm, neuro evalution

  - scope:
      path: "_tutorials/machine-learning/keras"
    values:
      layout: tutorial-post
      series: Keras
      tut-permalink: /tutorials/machine-learning/keras/
      category: keras
      keywords: keras, 神经网络, tensorflow, theano

  - scope:
      path: "_tutorials/machine-learning/torch"
    values:
      layout: tutorial-post
      series: PyTorch
      tut-permalink: /tutorials/machine-learning/torch/
      category: torch
      keywords: Torch, pytorch, 神经网络

  - scope:
      path: "_tutorials/machine-learning/sklearn"
    values:
      layout: tutorial-post
      series: Sklearn
      tut-permalink: /tutorials/machine-learning/sklearn/
      category: sklearn
      keywords: sklearn, scikit-learn, 机器学习


  - scope:
      path: "_tutorials/machine-learning/tensorflow"
    values:
      layout: tutorial-post
      series: Tensorflow
      tut-permalink: /tutorials/machine-learning/tensorflow/
      category: tensorflow
      keywords: tensorflow, tensorboard, 机器学习, 神经网络

  - scope:
      path: "_tutorials/machine-learning/theano"
    values:
      layout: tutorial-post
      series: Theano
      tut-permalink: /tutorials/machine-learning/theano/
      category: theano
      keywords: theano, 机器学习, 神经网络

  - scope:
      path: "_tutorials/data-manipulation/np-pd"
    values:
      layout: tutorial-post
      series: Numpy & Pandas
      tut-permalink: /tutorials/data-manipulation/np-pd/
      category: np-pd
      keywords: numpy, pandas, 数据, 处理

  - scope:
      path: "_tutorials/data-manipulation/plt"
    values:
      layout: tutorial-post
      series: Matplotlib
      tut-permalink: /tutorials/data-manipulation/plt/
      category: plt
      keywords: matplotlib, plt, 数据可视化

  - scope:
      path: "_tutorials/python-basic/basic"
    values:
      layout: tutorial-post
      series: Python 基础
      tut-permalink: /tutorials/python-basic/basic/
      category: Python 基础
      keywords: python, 基础

  - scope:
      path: "_tutorials/python-basic/multiprocessing"
    values:
      layout: tutorial-post
      series: 多进程 Multiprocessing
      tut-permalink: /tutorials/python-basic/multiprocessing/
      category: multiprocessing
      keywords: python, 基础, 多进程, multiprocessing

  - scope:
      path: "_tutorials/python-basic/threading"
    values:
      layout: tutorial-post
      series: 多线程 Threading
      tut-permalink: /tutorials/python-basic/threading/
      category: threading
      keywords: python, 基础, 多线程, threading


  - scope:
      path: "_tutorials/python-basic/tkinter"
    values:
      layout: tutorial-post
      series: 窗口 Tkinter
      tut-permalink: /tutorials/python-basic/tkinter/
      category: tkinter
      keywords: python, 基础, GUI, 窗口, tkinter, tk

  - scope:
      path: "_tutorials/python-basic/basic"
    values:
      layout: tutorial-post
      series: Python 基础
      tut-permalink: /tutorials/python-basic/basic/
      category: basic
      keywords: python, 基础

  - scope:
      path: "_tutorials/others/git"
    values:
      layout: tutorial-post
      series: Git 版本管理
      tut-permalink: /tutorials/others/git/
      category: git
      keywords: 其他, git, VCS
      published: true
