collections:
  ML_intro:
    output: true
  tensorflow:
    output: true
  backup:
    output: true

markdown: kramdown
permalink: pretty
url: https://morvanzhou.github.io
baseurl:

exclude: ['README.md']